### PR TITLE
Fix nullability warnings

### PR DESCRIPTION
**Pull request by DrBeak1**
# Overview

Adds. nullability specifiers to remove warnings.

## Testing

* All tests still pass.

## Screenshots

NA

### CODE REVIEW

**Comment by DrBeak1** [comment]
@MarkWaldron @reedflinch Just pinging folks again to see if it's possible to get this merged. Please let me know either way. Ty.

**Comment by reedflinch** [comment]
Thanks @DrBeak1, speaking with the team about this

**Comment by MarkWaldron** [comment]
@DrBeak1 Hey! Thanks for opening this PR. I'll chat with the team about this and see if we can get it tested on our end. Just an FYI - we will be releasing new (and very much improved) versions of the SDKs in the next few weeks.

**Comment by DrBeak1** [comment]
@MarkWaldron just checking for any update on this? If you guys decided not to allow the merge, that's OK - just want to know if I should close this and scrap the ticket on my teams board. Ty!

**Comment by DrBeak1** [comment]
@MarkWaldron weekly check-in. Any updates?

**Comment by GalCohen** [comment]
@DrBeak1  thanks for taking the time to do this. 

Any updates on this from the Kustomer team? @reedflinch  / @MarkWaldron  ?  This is generating quite a lot warnings in our projects...

**Comment by DrBeak1** [comment]
Hey @GalCohen nope. My only dialog with the team is here in this thread.

**Comment by DrBeak1** [comment]
@MarkWaldron @reedflinch weekly check-in. Any updates on this?

**Comment by MarkWaldron** [comment]
@DrBeak1 Hey - no update here. We've been swamped working towards our new Swift and Kotlin SDK releases. I'll check in with QA next week to see if they can give this a run of testing to verify it works for everything, but I can't guarantee that we will be able to get it merged in. Apologies for the delay

**Comment by DrBeak1** [comment]
@MarkWaldron thanks for the update. I really appreciate it. If the new SDKs are going to remove these warnings (guessing they will) then we can just note that in our ticket, close it, and live with the warnings until then. If you can confirm, I'll also close this pull request. Will the new SDK continue to support iOS 13?

**Comment by MarkWaldron** [comment]
@DrBeak1 All the null warnings should go away and we will support iOS 11 through 14. We will be announcing it early next week to our customers in the product newsletter with a form to request access

**Comment by DrBeak1** [comment]
@MarkWaldron thanks so much. I really appreciate you getting back to me. For now, we'll close our ticket with the expectation that we'll be able to jump over to the Swift version once things are completed on your end.

**Comment by DrBeak1** [comment]
Closing: New Kustomer SDK release is imminent which will resolve warning issues.

**Pull request closed without merging**
